Fail similar to Gradle itself when run with JRE instead of JDK
When Gradle is run with a JRE, Jvm.current().getToolsJar() returns
null, which caused a NPE in our SelfFirstClassLoader clinit that
manifested only as a NoClassDefFoundError.
This change explicitly tests for that situation and throws an
exception with a clear error message (borrowed from Gradle's
internal JdkTools class used by the JavaCompiler)